-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Nov 03, 2015 at 03:20 PM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `woody`
--

-- --------------------------------------------------------

--
-- Table structure for table `woody_table`
--

CREATE TABLE IF NOT EXISTS `woody_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `film_name` varchar(80) NOT NULL,
  `release_date` varchar(15) NOT NULL,
  `genre` varchar(50) DEFAULT NULL,
  `summary` text,
  `wrote` bit(1) DEFAULT NULL,
  `acted` bit(1) DEFAULT NULL,
  `directed` bit(1) DEFAULT NULL,
  `runtime` int(11) DEFAULT NULL,
  `female_lead` varchar(30) DEFAULT NULL,
  `male_lead` varchar(50) DEFAULT NULL,
  `quote` mediumtext,
  `image_location` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=73 ;

--
-- Dumping data for table `woody_table`
--

INSERT INTO `woody_table` (`id`, `film_name`, `release_date`, `genre`, `summary`, `wrote`, `acted`, `directed`, `runtime`, `female_lead`, `male_lead`, `quote`, `image_location`) VALUES
(1, 'What''s New Pussycat?', '1965', 'comedy', 'A playboy who refuses to give up his hedonistic lifestyle to settle down and marry his true love seeks help from a demented psychoanalyst who is having romantic problems of his own.', b'1', b'1', b'0', 108, 'n/a', 'n/a', 'Michael James: Did you find a job?\r\n\r\nVictor Skakapopulis: Yeah, I got something at the striptease. I help the girls dress and undress.\r\n\r\nMichael James: Nice job.\r\n\r\nVictor Skakapopulis: Twenty francs a week.\r\n\r\nMichael James: Not very much.\r\n\r\nVictor Skakapopulis: It''s all I can afford. ', 'pussycat.jpg'),
(2, 'What''s Up, Tiger Lily?', '1966', 'adventure comedy crime', 'In comic Woody Allen''s film debut, he took the Japanese action film "International Secret Police: Key of Keys" and re-dubbed it, changing the plot to make it revolve around a secret egg salad recipe.', b'1', b'1', b'1', 80, NULL, NULL, 'Woody Allen: They wanted in Hollywood to make the definitive spy picture. And they came to me to supervise the project, you know, because I think that, if you know me at all, you know that death is my bread and danger my butter - oh, no, danger''s my bread, and death is my butter. No, no, wait. Danger''s my bread, death - no, death is - no, I''m sorry. Death is my - death and danger are my various breads and various butters. ', 'tiger.jpg'),
(3, 'Casino Royale', '1967', 'comedy', 'In an early spy spoof, aging Sir James Bond comes out of retirement to take on SMERSH.', b'0', b'1', b'0', 131, NULL, NULL, 'Jimmy Bond: You can''t shoot me! I have a very low threshold of death. My doctor says I can''t have bullets enter my body at any time. ', 'casino.jpg'),
(4, 'Don''t Drink the Water', '1969', 'comedy', 'The Hollander family''s European vacation is interrupted when their plane is forced to land in Vulgaria. The Hollanders leave the plane to take pictures which results in accusations of spying. Chased by Vulgarian soldiers, they take refuge in the American Embassy under the protection of the absent ambassador''s hapless son. ', b'1', b'0', b'0', 100, NULL, NULL, 'Walter Hollander: I don''t eat oysters. You have to eat them alive. I like my food dead. Not sick, not wounded -- dead! ', 'drinkwater.jpg'),
(5, 'Take the Money and Run', '1969', 'comedy crime', 'The life and times of Virgil Starkwell, inept bank robber.', b'1', b'1', b'1', 85, NULL, NULL, 'Louise: He is always very depressed. I think that if he''d been a successful criminal, he would have felt better. You know, he never made the ''ten most wanted'' list. It''s very unfair voting; it''s who you know. ', 'takemoney.jpg'),
(6, 'Bananas', '1971', 'comedy', 'When a bumbling New Yorker is dumped by his activist girlfriend, he travels to a tiny Latin American nation and becomes involved in its latest rebellion.', b'1', b'1', b'1', 82, NULL, NULL, 'Nancy: Have you ever been to Denmark?\r\n\r\nFielding Mellish: I''ve been, yes... to the Vatican.\r\n\r\nNancy: The Vatican? The Vatican is in Rome.\r\n\r\nFielding Mellish: Well, they were doing so well in Rome that they opened one in Denmark. ', 'banana.jpg'),
(7, 'Play It Again, Sam', '1972', 'comedy romance', 'A neurotic film critic tries to get over his wife leaving him by dating again, much by the help of a married couple and his alter ego, Humphrey Bogart.', b'1', b'1', b'0', 85, NULL, NULL, 'Allan: That''s quite a lovely Jackson Pollock, isn''t it?\r\n\r\nMuseum Girl: Yes, it is.\r\n\r\nAllan: What does it say to you?\r\n\r\nMuseum Girl: It restates the negativeness of the universe. The hideous lonely emptiness of existence. Nothingness. The predicament of Man forced to live in a barren, Godless eternity like a tiny flame flickering in an immense void with nothing but waste, horror and degradation, forming a useless bleak straitjacket in a black absurd cosmos.\r\n\r\nAllan: What are you doing Saturday night?\r\n\r\nMuseum Girl: Committing suicide.\r\n\r\nAllan: What about Friday night? ', 'playitsam.jpg'),
(8, 'Everything You Always Wanted to Know About Sex* (*But Were Afraid to Ask)', '1972', 'comedy', 'Seven segments related to one another only in that they all purport to be based on sections of the book by David Reuben. The segments range from "Do Aphrodisiacs Work?" in which a court jester gives an aphrodisiac to the Queen and is, in the end, beheaded to "What Happens During Ejaculation?" in which we watch ''control central'' during a successful seduction. ', b'1', b'1', b'1', 88, NULL, NULL, 'Victor Shakapopulis: I don''t know if you''ve read my book, "Advanced Sexual Positions: How to Achieve Them Without Laughing." ', 'everythingyouwanted.jpg'),
(9, 'Sleeper', '1973', 'comedy scifi', 'A nerdish store owner is revived out of cryostasis into a future world to fight an oppressive government.', b'1', b'1', b'1', 88, NULL, NULL, 'Luna Schlosser: Oh, I see. You don''t believe in science, and you also don''t believe that political systems work, and you don''t believe in God, huh?\r\n\r\nMiles Monroe: Right.\r\n\r\nLuna Schlosser: So then, what do you believe in?\r\n\r\nMiles Monroe: Sex and death - two things that come once in a lifetime... but at least after death, you''re not nauseous. ', 'sleeper.jpg'),
(10, 'Love and Death', '1975', 'comedy war', 'In czarist Russia, a neurotic soldier and his distant cousin formulate a plot to assassinate Napoleon.', b'1', b'1', b'1', 85, NULL, NULL, 'Sonja: To love is to suffer. To avoid suffering one must not love. But then one suffers from not loving. Therefore, to love is to suffer; not to love is to suffer; to suffer is to suffer. To be happy is to love. To be happy, then, is to suffer, but suffering makes one unhappy. Therefore, to be unhappy, one must love or love to suffer or suffer from too much happiness. I hope you''re getting this down. ', 'lovedeath.jpg'),
(11, 'The Front', '1976', 'comedy drama', 'A cashier poses as a writer for blacklisted talents to submit their work through, but the injustice around him pushes him to take a stand.', b'0', b'1', b'0', 95, NULL, NULL, 'Howard Prince: Swimming''s not a sport, swimming''s what you do so that you shouldn''t drown. ', 'front.jpg'),
(12, 'Annie Hall', '1977', 'comedy romance', 'Neurotic New York comedian Alvy Singer falls in love with the ditsy Annie Hall.', b'1', b'1', b'1', 93, NULL, NULL, 'Alvy Singer: I feel that life is divided into the horrible and the miserable. That''s the two categories. The horrible are like, I don''t know, terminal cases, you know, and blind people, crippled. I don''t know how they get through life. It''s amazing to me. And the miserable is everyone else. So you should be thankful that you''re miserable, because that''s very lucky, to be miserable. ', 'anniehall.jpg'),
(13, 'Interiors', '1978', 'drama', 'Three sisters find their lives spinning out of control in the wake of their parents'' sudden, unexpected divorce.', b'1', b'0', b'1', 99, NULL, NULL, 'Pearl: You''ll live to be a hundred if you give up all the things that make you want to.', 'interiors.jpg'),
(14, 'Manhattan', '1979', 'comedy drama romance', 'The life of a divorced television writer dating a teenage girl is further complicated when he falls in love with his best friend''s mistress.', b'1', b'1', b'1', 96, NULL, NULL, 'Isaac Davis: My analyst warned me, but you were so beautiful I got another analyst. ', 'manhattan.jpg'),
(15, 'Stardust Memories', '1980', 'comedy drama', 'While attending a retrospect of his work, a filmmaker recalls his life and his loves: the inspirations for his films.', b'1', b'1', b'1', 88, NULL, NULL, 'Sandy Bates: You can''t control life. It doesn''t wind up perfectly. Only-only art you can control. Art and masturbation. Two areas in which I am an absolute expert. ', 'stardust.jpg'),
(16, 'A Midsummer Night''s Sex Comedy', '1982', 'comedy', 'A wacky inventor and his wife invite two other couples for a weekend party at a romantic summer house in the 1900s countryside.', b'1', b'1', b'1', 88, NULL, NULL, 'Andrew: Sex alleviates tension and love causes it. ', 'midsummernight.jpg'),
(17, 'Zelig', '1983', 'comedy', '"Documentary" about a man who can look and act like whoever he''s around, and meets various famous people.', b'1', b'1', b'1', 79, NULL, NULL, 'Leonard Zelig: I''m 12 years old. I run into a Synagogue. I ask the Rabbi the meaning of life. He tells me the meaning of life... But, he tells it to me in Hebrew. I don''t understand Hebrew. Then he wants to charge me six hundred dollars for Hebrew lessons. ', 'zelig.jpg'),
(18, 'Broadway Danny Rose', '1984', 'comedy', 'In his attempts to reconcile a lounge singer with his mistress, a hapless talent agent is mistaken as her lover by a jealous gangster.', b'1', b'1', b'1', 84, NULL, NULL, 'Danny Rose: You know what my philosophy of life is? That it''s important to have some laughs, but you gotta suffer a little too, because otherwise you miss the whole point to life. ', 'broadwaydanny.jpg'),
(19, 'The Purple Rose of Cairo', '1985', 'comedy fantasy romance', 'In 1930s New Jersey, a movie character walks off the screen and into the real world.', b'1', b'0', b'1', 82, NULL, NULL, 'Cecilia: I just met a wonderful new man. He''s fictional but you can''t have everything. ', 'purplerose.jpg'),
(20, 'Hannah and Her Sisters', '1986', 'comedy drama', 'Between two Thanksgivings, Hannah''s husband falls in love with her sister Lee, while her hypochondriac ex-husband rekindles his relationship with her sister Holly.', b'1', b'1', b'1', 106, NULL, NULL, 'Mickey: A week ago I bought a rifle, I went to the store - I bought a rifle! I was gonna, you know, if they told me I had a tumor, I was gonna kill myself. The only thing that might-ve stopped me - MIGHT''VE - is that my parents would be devastated. I would have to shoot them also, first. And then I have an aunt and uncle - you know - it would''ve been a blood bath. ', 'hannahsisters.jpg'),
(21, 'Radio Days', '1987', 'comedy', 'A nostalgic look at radio''s golden age focusing on one ordinary family and the various performers in the medium.', b'1', b'1', b'1', 85, NULL, NULL, 'Rabbi Baumel: Radio... It''s all right once in a while. Otherwise it tends to induce bad values, false dreams, lazy habits. Listening to these stories of foolishness and violence... this is no way for a boy to grow up.\r\n\r\nJoe: You speak the truth, my faithful Indian companion.\r\n\r\nRabbi Baumel: To a rabbi you say "my faithful Indian companion"?\r\n\r\n[hits him in a head] ', 'radiodays.jpg'),
(22, 'September', '1987', 'drama', 'At a summer house in Vermont, neighbor Howard falls in love with Lane, who''s in a relationship with Peter, who''s falling for Stephanie, who''s married with children.', b'1', b'0', b'1', 82, NULL, NULL, 'Diane: The Richmonds are flooded, electricity''s gone off. God is testing us and I for one am gonna be prepared. Where''s the vodka? ', 'september.jpg'),
(23, 'Another Woman', '1988', 'drama', 'Facing a mid-life crisis, a woman rents an apartment next to a psychiatrist''s office to write a new book, only to become drawn to the plight of a pregnant woman seeking that doctor''s help.', b'1', b'0', b'1', 84, NULL, NULL, 'Marion: I closed the book, and felt this strange mixture of wistfulness and hope, and I wondered if a memory is something you have or something you''ve lost. For the first time in a long time, I felt at peace. ', 'anotherwoman.jpg'),
(24, 'New York Stories', '1989', 'comedy drama romance', 'A middle-aged artist obsessed with his pretty young assistant, a precocious 12 year old living in a hotel, and a neurotic lawyer with a possessive mother make up three Gotham tales.', b'1', b'1', b'1', 124, NULL, NULL, 'Sheldon: You got a nice place here. What time does the cobra come out? ', 'nystories.jpg'),
(25, 'Crimes and Misdemeanors', '1989', 'comedy drama', 'An ophthalmologist''s mistress threatens to reveal their affair to his wife, while a married documentary filmmaker is infatuated by another woman.', b'1', b'1', b'1', 104, NULL, NULL, 'Halley Reed: He wants to produce something of mine.\r\n\r\nClifford Stern: Yeah. Your first child. ', 'crimesmisdemeanors.jpg'),
(26, 'Alice', '1990', 'comedy fantasy romance', 'A spoiled Manhattan housewife re-evaluates her life after visiting a Chinatown healer.', b'1', b'0', b'1', 102, NULL, NULL, 'Muse: Yeah, I know Professor Davis. He''s trying to get you into the sack.\r\n\r\nAlice: No!\r\n\r\nMuse: Yeah, it''s the main reason he teaches: female pupils.\r\n\r\nAlice: No, he''s, he''s very deep! He''s not like that.\r\n\r\nMuse: Yeah, ''very deep'' is exactly where he wants to put it. ', 'alice.jpg'),
(27, 'Scenes from a Mall', '1991', 'comedy', 'On their 16th anniversary a married couple''s trip to a Beverly Hills mall becomes the stage for personal revelations and deceptions.', b'0', b'1', b'0', 89, NULL, NULL, 'Nick Fifer: How many 16th anniversaries does a person have in a lifetime? One... maybe two. ', 'scenesfrommall.jpg'),
(28, 'Shadows and Fog', '1991', 'comedy', 'With a serial strangler on the loose, a bookkeeper wanders around town searching for the vigilante group intent on catching the killer.', b'1', b'1', b'1', 85, NULL, NULL, 'Kleinmann: Uh, I''ve... I''ve never paid for sex in my life.\r\n\r\nProstitute: Oh, you just think you haven''t. ', 'shadowsfog.jpg'),
(29, 'Husbands and Wives', '1992', 'comedy drama romance', 'When their best friends announce that they''re separating, a professor and his wife discover the faults in their own marriage.', b'1', b'1', b'1', 108, NULL, NULL, 'Judy: You use sex to express every emotion except love. ', 'husbandswives.jpg'),
(30, 'Manhattan Murder Mystery', '1993', 'comedy mystery', 'A middle-aged couple suspects foul play when their neighbor''s wife suddenly drops dead.', b'1', b'1', b'1', 104, NULL, NULL, 'Hotel night clerk: You are with police?\r\n\r\nLarry Lipton: Yes, I''m a detective. They lowered the height requirement. ', 'murdermystery.jpg'),
(31, 'Bullets over Broadway', '1994', 'comedy crime', 'In 1920s New York, a struggling playwright is forced to cast a mobster''s talentless girlfriend in his latest drama in order to get it produced.', b'1', b'0', b'1', 98, NULL, NULL, 'Helen Sinclair: Two martinis please, very dry.\r\n\r\nDavid Shayne: How''d you know what I drank?\r\n\r\nHelen Sinclair: Oh, you want one too? Three. ', 'bulletsbroadway.jpg'),
(32, 'Don''t Drink The Water', '1994', 'comedy', 'The Hollander family''s European vacation is interrupted when their plane is forced to land in Vulgaria. The Hollanders leave the plane to take pictures which results in accusations of spying. Chased by Vulgarian soldiers, they take refuge in the American Embassy under the protection of the absent ambassador''s hapless son. ', b'1', b'1', b'1', 100, NULL, NULL, 'Walter Hollander: I don''t eat oysters. You have to eat them alive. I like my food dead. Not sick, not wounded -- dead! ', 'drinkwater.jpg'),
(33, 'Mighty Aphrodite', '1995', 'comedy fantasy romance', 'When he discovers his adopted son is a genius, a New York sportswriter seeks out the boy''s birth mother: a prostitute.', b'1', b'1', b'1', 95, NULL, NULL, 'Lenny Weinrib: Achilles only had an Achilles heel, I have an entire Achilles body. ', 'aphrodite.jpg'),
(34, 'Everyone Says I Love You', '1996', 'comedy musical romance', 'A New York girl sets her father up with a beautiful woman in a shaky marriage while her half sister gets engaged.', b'1', b'1', b'1', 101, NULL, NULL, 'Bob: I never believed in God. No, I didn''t even as a little kid. I remember this. I used to think even if he exists, he''s done such a terrible job, it''s a wonder people don''t get together and file a class action suit against him. ', 'everyonesays.jpg'),
(35, 'Deconstructing Harry', '1997', 'comedy', 'Suffering from writer''s block and eagerly awaiting his writing award, Harry Block remembers events from his past and scenes from his best-selling books as characters, real and fictional, come back to haunt him.', b'1', b'1', b'1', 96, NULL, NULL, 'Harry Block: All people know the same truth. Our lives consist of how we chose to distort it. ', 'harry.jpg'),
(36, 'Celebrity', '1998', 'comedy drama', 'The fortunes of a husband and wife differ drastically after they divorce.', b'1', b'0', b'1', 113, NULL, NULL, 'Robin Simon: I''ve become the person I''ve always hated, but I''m happier. ', 'celebrity.jpg'),
(37, 'Sweet and Lowdown', '1999', 'comedy drama music', 'In the 1930s, fictional jazz guitarist Emmet Ray idolizes Django Reinhardt, faces gangsters and falls in love with a mute.', b'1', b'1', b'1', 95, NULL, NULL, 'Emmet Ray: Wanna go to the dump and shoot some rats? ', 'sweetlowdown.jpg'),
(38, 'Small Time Crooks', '2000', 'comedy crime', 'A loser of a crook and his wife strike it rich when a botched bank job''s cover business becomes a spectacular success.', b'1', b'1', b'1', 95, NULL, NULL, 'Ray: Remember my nickname when we were in the joint?\r\n\r\nBenny: The Brain?\r\n\r\nRay: The Brain. That''s what the guys used to call me, right?\r\n\r\nBenny: But, Ray! That was sarcastic! ', 'smalltime.jpg'),
(39, 'Picking Up the Pieces', '2000', 'comedy fantasy', 'A small New Mexican village discovers a severed hand that is considered a miracle of God, when it actually belongs to a murdered spouse with a husband in search of it.', b'0', b'1', b'0', 95, NULL, NULL, 'Tex Cowley: She had a boyfriend before me who was in with the mob, and she testified against him and, you know, he didn''t take it too kindly... So we came out to Texas, eh, primarily for the air... Actually, we, eh, we wanted to keep breathing it... ', 'pickingpieces.jpg'),
(40, 'The Curse of the Jade Scorpion', '2001', 'comedy crime mystery', 'An insurance investigator and an efficency expert who hate each other are both hypnotized by a crooked hypnotist with a jade scorpion into stealing jewels.', b'1', b'1', b'1', 103, NULL, NULL, 'C.W.: I hate her just like I hate that German Chancellor with the moustache. ', 'jadescorpion.jpg'),
(41, 'Hollywood Ending', '2002', 'comedy romance', 'A director is forced to work with his ex-wife, who left him for the boss of the studio bankrolling his new film. But the night before the first day of shooting, he develops a case of psychosomatic blindness.', b'1', b'1', b'1', 114, NULL, NULL, 'Val: We had sex.\r\n\r\nEllie: Yes, we had sex. But we never talked.\r\n\r\nVal: Sex is better than talk. Ask anybody in this bar. Talk is what you suffer through so you can get to sex. ', 'hollywoodending.jpg'),
(42, 'Anything Else', '2003', 'comedy romance', 'Jerry Falk learns that lesson the hard way when he falls head over heels in love with a beautiful but flighty girl, Amanda.', b'1', b'1', b'1', 108, NULL, NULL, 'David Dobel: I broke up with this girl, and they put me with a psychiatrist who said, "Why did you get so depressed, and do all those things you did?" I said, "I wanted this girl and she left me." And he said, "Well, we have to look into that." And I said, "There''s nothing to look into. I wanted her and she left me." And he said, "Well, why are you feeling so intense?" And I said, "Cause I want the girl." And he said, "What''s underneath it?" And I said, "Nothing." He said, "I''ll have to give you medication." I said, "I don''t want medication. I want the girl." And he said, "We have to work this through." So, at that point, I took a fire extinguisher from the casement and struck him across the back of his neck. ', 'anythingelse.jpg'),
(43, 'Melinda and Melinda', '2004', 'comedy drama romance', 'Two alternating stories about Melinda''s (Mitchell) attempts to straighten out her life.', b'1', b'0', b'1', 99, NULL, NULL, 'Susan: I wish we could afford a place in the Hamptons. Everybody who''s anybody has one.\r\n\r\nHobie: Yeah, but if you''re somebody who''s nobody, it''s no fun to be around anybody who''s everybody. ', 'melinda.jpg'),
(44, 'Match Point', '2005', 'drama romance thriller', 'At a turning point in his life, a former tennis pro falls for an actress who happens to be dating his friend and soon-to-be brother-in-law.', b'1', b'0', b'1', 124, NULL, NULL, 'Christopher "Chris" Wilton: The man who said "I''d rather be lucky than good" saw deeply into life. People are afraid to face how great a part of life is dependent on luck. It''s scary to think so much is out of one''s control. There are moments in a match when the ball hits the top of the net, and for a split second, it can either go forward or fall back. With a little luck, it goes forward, and you win. Or maybe it doesn''t, and you lose. ', 'matchpoint.jpg'),
(45, 'Scoop', '2006', 'comedy mystery', 'An American journalism student in London scoops a big story, and begins an affair with an aristocrat as the incident unfurls.', b'1', b'1', b'1', 96, NULL, NULL, 'Sid Waterman: I was born into the Hebrew persuasion, but when I got older I converted to narcissism ', 'scoop.jpg'),
(46, 'Cassandra''s Dream', '2007', 'crime drama romance', 'The tale of two brothers with serious financial woes. When a third party proposes they turn to crime, things go bad and the two become enemies.', b'1', b'0', b'1', 110, NULL, NULL, 'Ian: Would you sleep with a director to get a part?\r\n\r\nAngela: Well, that depends on the part, and who the director is, and how much I''d had to drink.\r\n\r\nIan: It''s not a very comforting answer.\r\n\r\nAngela: I didn''t like the question. ', 'cassandra.jpg'),
(47, 'Vicky Cristina Barcelona', '2008', 'drama romance', 'Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.', b'1', b'0', b'1', 97, NULL, NULL, 'Juan Antonio: Maria Elena used to say that only unfulfilled love can be romantic. ', 'vicky.jpg'),
(48, 'Whatever Works', '2009', 'comedy romance', 'A middle-aged, misanthropic divorcée from New York City surprisingly enters a fulfilling, Pygmalion-type relationship with a much younger, unsophisticated Southern girl.', b'1', b'0', b'1', 92, NULL, NULL, 'Boris Yellnikoff: That''s why I can''t say enough times, whatever love you can get and give, whatever happiness you can filch or provide, every temporary measure of grace, whatever works. ', 'whateverworks.jpg'),
(49, 'You Will Meet a Tall Dark Stranger', '2010', 'comedy drama romance', 'Sally''s parents'' marriage breaks up when her father undergoes a mid-life crisis and impulsively weds a prostitute as Sally''s own marriage also begins to disintegrate.', b'1', b'0', b'1', 100, NULL, NULL, 'Sally: That cheap tart is what he left my mother for? Actress, my foot! The only acting she''s ever done is faking an orgasm. ', 'talldarkstranger.jpg'),
(50, 'Midnight in Paris', '2011', 'comedy fantasy romance', 'While on a trip to Paris with his fiancée''s family, a nostalgic screenwriter finds himself mysteriously going back to the 1920s every day at midnight.', b'1', b'0', b'1', 94, NULL, NULL, 'Gil: Yes, but you''re a surrealist! I''m a normal guy! ', 'midnightparis.jpg'),
(51, 'To Rome with Love', '2012', 'comedy romance', 'The lives of some visitors and residents of Rome and the romances, adventures and predicaments they get into.', b'1', b'1', b'1', 112, NULL, NULL, 'Michelangelo: He sings for pleasure, not money.\r\n\r\nJerry: Well, there''s a great deal of pleasure in money. You know, you... it''s green and crinkly. You can fondle the bills. ', 'romewithlove.jpg'),
(52, 'Blue Jasmine', '2013', 'drama romance', 'A New York socialite, deeply troubled and in denial, arrives in San Francisco to impose upon her sister. She looks a million, but isn''t bringing money, peace, or love...', b'1', b'0', b'1', 99, NULL, NULL, 'Jasmine: Anxiety, nightmares and a nervous breakdown, there''s only so many traumas a person can withstand until they take to the streets and start screaming. ', 'jasmine.jpg'),
(53, 'Fading Gigolo', '2014', 'comedy', 'Fioravante decides to become a professional Don Juan as a way of making money to help his cash-strapped friend, Murray. With Murray acting as his "manager", the duo quickly finds themselves caught up in the crosscurrents of love and money.', b'0', b'1', b'0', 90, NULL, NULL, 'Othella: If you hurt a hair on his head, I will pull a Michael Corleone on you.\r\n\r\nDovi: Michael Corleone? Who''s that? Is that a threat? ', 'gigolo.jpg'),
(54, 'Magic in the Moonlight', '2014', 'comedy romance', 'A romantic comedy about an Englishman brought in to help unmask a possible swindle. Personal and professional complications ensue.', b'1', b'0', b'1', 97, NULL, NULL, 'Stanley: I can''t forgive you, only God can forgive you.\r\n\r\nSophie: But you said there is no God.\r\n\r\nStanley: Precisely my point. ', 'magicmoonlight.jpg'),
(55, 'Irrational Man', '2015', 'drama mystery', 'A tormented philosophy professor finds a will to live when he commits an existential act.', b'1', b'0', b'1', 95, NULL, NULL, 'Abe: So much of philosophy is just verbal masturbation. ', 'irrational.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
